export enum AUDIT_ACTION {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  RESTORE = 'RESTORE',
  STATUS_CHANGE = 'STATUS_CHANGE',
  PASSWORD_CHANGE = 'PASSWORD_CHANGE',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  BULK_UPDATE = 'BULK_UPDATE',
  PROTECTED_FIELDS_UPDATE = 'PROTECTED_FIELDS_UPDATE'
}

export enum AUDIT_ENTITY_TYPE {
  USER = 'USER',
  PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST',
  AUDIT_LOG = 'AUDIT_LOG',
  SESSION = 'SESSION',
  WORKSHOP = 'WORKSHOP',
  REGISTRATION = 'REGISTRATION',
  OTHER = 'OTHER'
}

export enum AUDIT_STATUS {
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED'
}
