export const ERROR_MESSAGES = {
  INTERNAL_SERVER_ERR: 'Internal server error',
  BAD_REQUEST: 'Bad request',
  CONFLICT: 'Conflict',
  FORBIDDEN: 'Forbidden',
  NOT_FOUND: 'Not found',
  TOO_MANY_REQUESTS: 'Too many requests',
  UNPROCESSABLE_ENTITY: 'Unprocessable entity',
  UNAUTHORIZED: 'Unauthorized',
  REFRESH_TOKEN_NOT_FOUND: 'Refresh token not found',
  REFRESH_TOKEN_INVALID_OR_EXPIRED: 'Refresh token is invalid or expired',
  USER_NOT_FOUND: 'User not found',
  ROUTE_NOT_FOUND: 'Route not found',
  USER_ALREADY_EXISTS: 'User with this username already exists.',
  USER_NAME_ALREADY_EXISTS: 'User name already exists, try another one',
  INVALID_CREDENTIALS: 'Invalid credentials',
  INVALID_AUTHORIZATION_HEADER: 'Invalid authorization header',
  INVALID_TOKEN: 'Invalid token',
  TOKEN_EXPIRED: 'Token expired',
  SESSION_EXPIRED: 'Session expired',
  SESSION_NOT_FOUND: 'Session not found',
  AUTHENTICATION_FAILED: 'Authentication failed',
  AUDIT_LOG_NOT_FOUND: 'Audit log not found',
  SUPER_ADMIN_ONLY_ACTION: 'This action can only be performed by super administrators',
  ADMIN_ONLY_ACTION: 'This action can only be performed by administrators',
  CURRENT_PASSWORD_REQUIRED: 'Current password is required to change password',
  INVALID_OBJECT_ID: 'The provided ID is not a valid Object ID.',
  SAME_PASSWORD: 'New password cannot be the same as the current password',
  INVALID_RESET_TOKEN: 'Invalid reset token',

  // Notification
  NOTIFICATION_NOT_FOUND: 'Notification not found',
  NOT_AUTHORIZED_TO_VIEW_NOTIFICATION: 'Not authorized to view this notification',
  NOT_AUTHORIZED_TO_UPDATE_NOTIFICATION: 'Not authorized to update this notification',

  // Workshop & Registration
  WORKSHOP_NOT_FOUND: 'Workshop not found',
  WORKSHOP_ALREADY_EXISTS: 'A workshop with this code already exists',
  WORKSHOP_AT_CAPACITY: 'Workshop is at full capacity. No seats available.',
  WORKSHOP_NOT_SCHEDULED: 'Workshop is not open for registration',
  REGISTRATION_NOT_FOUND: 'Registration not found',
  REGISTRATION_ALREADY_CANCELLED: 'Registration is already cancelled',
  ATTENDEE_ALREADY_REGISTERED: 'This attendee already has an active registration for this workshop',
  ATTENDEE_ALREADY_WAITLISTED: 'This attendee is already queued on the waitlist for this workshop',
  ATTENDEE_ALREADY_CONFIRMED: 'This attendee already has an active confirmed seat for this workshop',
  MANAGER_ONLY_ACTION: 'This action can only be performed by managers',
  STAFF_OR_MANAGER_ONLY_ACTION: 'This action can only be performed by staff or managers',
  ADMIN_RESTRICTED_ACTION: 'Administrators are restricted from viewing or modifying workshops and registrations'
};
