export const ERROR_MESSAGES = {
  INTERNAL_SERVER_ERR: 'Internal server error',
  BAD_REQUEST: 'Bad request',
  UNKNOWN_ERR: 'Unknown Error',
  CONFLICT: 'Conflict',
  NOT_FOUND: 'Not found',
  TOO_MANY_REQUESTS: 'Too many requests',
  REFRESH_TOKEN_NOT_FOUND: 'Refresh token not found',
  REFRESH_TOKEN_INVALID_OR_EXPIRED: 'Refresh token is invalid or expired',
  UNPROCESSABLE_ENTITY: 'Unprocessable entity',
  UNAUTHORIZED: 'Unauthorized',
  USER_NOT_FOUND: 'User not found',
  ROUTE_NOT_FOUND: 'Route not found',
  USER_ALREADY_EXISTS: 'User already exists',
  INVALID_CREDENTIALS: 'Invalid credentials',
  INVALID_AUTHORIZATION_HEADER: 'Invalid authorization header',
  INVALID_TOKEN: 'Invalid token',
  TOKEN_EXPIRED: 'Token expired',
  SESSION_EXPIRED: 'Session expired',
  AUTHENTICATION_FAILED: 'Authentication failed',
};
